
BUILD=build

# Compile main by default
all: build

# Make the build directory if it doesn't exist
build:
	mkdir -p $(BUILD)
	# touch $(BUILD)/temp.txt

# Delete the build directory and program
clean:
	rm -rf $(BUILD)

# These rules do not correspond to a specific file
.PHONY: build clean